version: '3.4'

services:
  mongo:
    container_name: mongo.db
    restart: always
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=taskmanager
    networks:
      - mongo-compose-network
      
  mongoexpress:
    container_name: mongo.express
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge